# For RIM-CAC
# general setting.
views: 2
hidden_dim: 512
device: 0
seed: 42
wandb: true
experiment_id: 0
verbose: true
note: ''
project_name: 'DMRIB'
backbone:
  type: 'cnn'
dataset:
  name: 'EdgeMnist'
  class_num: 10
train:
  epochs: 150
  batch_size: 512
  optim: "adam"
  lr: 0.0005
  evaluate: 1
  scheduler: 'constant'
  lr_decay_rate: 0.9
  resume: false

consis_enc:
  enable: true
  backbone: 'resnet18'
  channels: 1
  max_pooling: false
  activation: 'relu'
  first_norm: false
  output_dim: 512
  project_dim: 128
fusion:
  type: "CV"
  pooling_method: 'mean'
vspecific:
  enable: true
  expands: 4
  kld_weight: 0.005
  latent_dim: 10
  best_view: 0
disent:
  lam: 0.01

valid_augmentation:
  crop_size: 32
  use_normalize: false
  normalize:
    mean: [0.1307]
    std: [0.3081]

selflabel:
  apply_class_balancing: True
  nheads: 1
  confidence_threshold: 0.99