
# general setting.
views: 2
hidden_dim: 512
device: 0
seed: 42
wandb: true
experiment_id: 0
verbose: true
note: ''
project_name: 'DMRIB'
backbone:
  type: 'cnn'
  init_method: 'xavier'
dataset:
  name: 'coil-20'
  class_num: 20
train:
  epochs: 150
  batch_size: 64
  optim: "adam"
  lr: 0.0005
  evaluate: 1
  scheduler: 'constant'
  lr_decay_rate: 0.9
  resume: false

consis_enc:
  enable: true
  backbone: 'resnet34'
  channels: 1
  max_pooling: true
  activation: 'relu'
  first_norm: false
  output_dim: 512
  project_dim: 128
fusion:
  type: "CV"
  pooling_method: 'mean'
vspecific:
  enable: true
  expands: 4
  kld_weight: 0.005
  latent_dim: 10
  best_view: 0
disent:
  lam: 0.01

valid_augmentation:
  crop_size: 64
  normalize:
    mean: [0.4901,]
    std: [0.2821,]

selflabel:
  apply_class_balancing: True
  confidence_threshold: 0.99
  nheads: 2
  