# general setting.
views: 2
hidden_dim: 512
device: 0
seed: 42
experiment_id: 0
verbose: true
project_name: 'DMRIB'
backbone:
  type: 'cnn'
  init_method: 'xavier'
dataset:
  name: 'EdgeMnist'
  class_num: 10
train:
  epochs: 500
  batch_size: 512
  optim: "sgd"
  lr: 0.003
  evaluate: 1
  scheduler: 'cosine'
  lr_decay_rate: 0.9

consis_enc:
  enable: true
  backbone: 'resnet18'
  channels: 1
  max_pooling: false
  activation: 'relu'
  first_norm: false
  output_dim: 512
  project_dim: 128
  temperature: 0.1
  loss_type: 'dcl'
fusion:
  pooling_method: 'mean'
# transformation
training_augmentation:
  hflip: false
  random_resized_crop:
    size: 32
    scale: [0.2, 1.0]
  # for simclr (weak augmentation)
  color_jitter_random_apply:
    p: 0.8
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1
  random_grayscale: 
    p: 0.2
  normalize:
    mean: [0.1307]
    std: [0.3081]


valid_augmentation:
  crop_size: 32
  normalize:
    mean: [0.1307]
    std: [0.3081]